music = {
    "blue eyes": "https://youtu.be/NbyHNASFi6U?si=NdExvnxP17tIozhX",
    "love dose": "https://youtu.be/TvngY4unjn4?si=Klb9ajmUNw62F9C0",
    "Tum Hi Ho": "https://youtu.be/Umqb9KENgmk",
    "Chaiyya Chaiyya": "https://youtu.be/PZ7-rpQoK1Y",
    "Kal Ho Naa Ho": "https://youtu.be/sK7riqg2mr4",
    "Tujh Mein Rab Dikhta Hai": "https://youtu.be/VhCajq5PZyg",
    "Pee Loon": "https://youtu.be/eg2Z5E_P_Jk",
    "Tera Ban Jaunga": "https://youtu.be/ToK6FATuoZQ",
    "Raabta": "https://youtu.be/0zJHdA0pL0I",
    "Tareefan": "https://youtu.be/B8gFZvPsVmQ",
    "Nashe Si Chadh Gayi": "https://youtu.be/PVxc5mIHVuQ",
    "Kabira": "https://youtu.be/jHNNMj5bNQw",
    "Tujhe Kitna Chahne Lage": "https://youtu.be/A0FZIwabctw",
    "Bekhayali": "https://youtu.be/VYpOFimB7ZA",
    "Ghungroo": "https://youtu.be/qQ3jzAV6x9g",
    "Dil Diyan Gallan": "https://youtu.be/sa1GWyWj5zQ",
    "Galliyan": "https://youtu.be/BddP6PYo2gs",
    "Tum Se Hi": "https://youtu.be/ONfQofh3SPc",
    "Kun Faya Kun": "https://youtu.be/T94PHkuydcw",
    "Tera Yaar Hoon Main": "https://youtu.be/J0VjvBzs5rs",
    "Zehnaseeb": "https://youtu.be/BMR6tFQy-8U",
    "Sun Saathiya": "https://youtu.be/UQH6TVaobUc",
    "Laung Da Lashkara": "https://youtu.be/gKXgVcuGmNw",
    "Kamariya": "https://youtu.be/WrrvHjv1_tM",
    "Kar Gayi Chull": "https://youtu.be/FvY1F21yb7E",
    "Kala Chashma": "https://youtu.be/k4yXQkG2s1E",
    "Badtameez Dil": "https://youtu.be/sTzVbFjD_qU",
    "Malhari": "https://youtu.be/Rm5g-O9KQUg",
    "London Thumakda": "https://youtu.be/r3yxxe66LXs",
    "Desi Girl": "https://youtu.be/IpEXEpg5xwQ",
    "Aankh Marey": "https://youtu.be/u5L4jBgGiEQ",
    "Bom Diggy Diggy": "https://youtu.be/6ZP6Fp-hkK0",
    "Zinda": "https://youtu.be/nZ9x3OdmOJ0",
    "Apna Time Aayega": "https://youtu.be/jFbqXkMTx1w",
    "Gallan Goodiyan": "https://youtu.be/u6BOC7CDUTQ",
    "Cutiepie": "https://youtu.be/16T9nD6R9ZM",
    "High Rated Gabru": "https://youtu.be/9J0sMZcpGAc",
    "Ban Ja Rani": "https://youtu.be/dXc5JX0NFak",
    "Tamma Tamma Again": "https://youtu.be/SBOkF3RJjOs",
    "Dilbar": "https://youtu.be/z0n1aQ3IxWI",
    "She Move It Like": "https://youtu.be/MtVQG3gNzvY",
    "Morni Banke": "https://youtu.be/4QpAZjHFQLQ",
    "Proper Patola": "https://youtu.be/nDHqzqg2h3M",
    "Bom Diggy": "https://youtu.be/1upZz3a-7iM",
    "Kaala Chashma": "https://youtu.be/k4yXQkG2s1E",
    "Saudagar Sauda Kar": "https://youtu.be/gnM2GsmBTfM",
    "Jab Tak": "https://youtu.be/L63DjXbqf7Q",
    "Muskurane": "https://youtu.be/xzvhZSr5G40",
    "Samjhawan": "https://youtu.be/k4yXQkG2s1E",
    "Jeene Laga Hoon": "https://youtu.be/m8I4rwrs6Uo",
    "Sooraj Dooba Hain": "https://youtu.be/4lSaf4FUNaQ",
    "Main Hoon Hero Tera": "https://youtu.be/ywKuwatS2f8",
    "Tum Mile": "https://youtu.be/N-Mt1yl7ARA",
    "Sun Raha Hai Na Tu": "https://youtu.be/3B5U6IMj6i8",
    "Mast Magan": "https://youtu.be/AOZuxCA7Wuc",
    "Pani Da Rang": "https://youtu.be/cEoN_WwPy5E",
    "Banjaara": "https://youtu.be/fdubeMFwuGs",
    "Phir Le Aaya Dil": "https://youtu.be/QT5jMtKxv2k",
    "Hasi Ban Gaye": "https://youtu.be/PP7pH4lr-BY",
    "Bol Do Na Zara": "https://youtu.be/Va0V1B4gYCo",
    "Kaun Tujhe": "https://youtu.be/0J8iZfx1ULY",
    "Enna Sona": "https://youtu.be/Se2gfFKpQfQ",
    "Jab Koi Baat": "https://youtu.be/bZxahqApycg",
    "Raatan Lambiyan": "https://youtu.be/gvyUuxdRdR4",
    "Shayad": "https://youtu.be/u7R6N0Yt4D4",
    "Hawayein": "https://youtu.be/aNQqoExfQsg",
    "Janam Janam": "https://youtu.be/XgFtQPgHyek",
    "Gerua": "https://youtu.be/Ek17-Sh7jtA",
    "The Breakup Song": "https://youtu.be/k4yXQkG2s1E",
    "Afreen Afreen": "https://youtu.be/kw4tT7SCmaY",
    "Tera Hone Laga Hoon": "https://youtu.be/L1gFgdSk21s",
    "Khairiyat": "https://youtu.be/AIXUgtNC4Kc",
    "Dil Mein Ho Tum": "https://youtu.be/xgqIv99R26E",
    "Tera Chehra": "https://youtu.be/TrBMyf8h4ZY",
    "Tujhko Jo Paaya": "https://youtu.be/AlTBkswI5KU",
    "Iktara": "https://youtu.be/RY0UXqJj4TY",
    "Khaab": "https://youtu.be/tS3fd1RZ0Kk",
    "Roke Na Ruke Naina": "https://youtu.be/MxMuTbvYQ5o",
    "O Re Piya": "https://youtu.be/YJ4OwQm6btw",
    "Tu Chale": "https://youtu.be/WbF0zOwqE9c",
    "Jiyein Kyun": "https://youtu.be/G9NLFzC5r2I",
    "Tu Jaane Na": "https://youtu.be/jMqLzjIRu6Q",
    "Dil Ibadat": "https://youtu.be/Db8fJgIRwBE",
    "Tujh Mein Rab Dikhta Hai": "https://youtu.be/VhCajq5PZyg",
    "Tera Mera Rishta": "https://youtu.be/Gj4rDxEXelU",
    "Agar Tum Saath Ho": "https://youtu.be/ojZ6rU7Z7QY",
    "Kaise Hua": "https://youtu.be/mylC2NF05p8",
    "Pal": "https://youtu.be/HxOHg8LUcAs",
    "Channa Mereya": "https://youtu.be/284Ov7ysmfA",
    "Duniyaa": "https://youtu.be/yQ_1GqgFQmE",
    "Nazm Nazm": "https://youtu.be/C_3d6GntKbk"
}
