music = {
    "blue eyes": "https://youtu.be/NbyHNASFi6U?si=NdExvnxP17tIozhX",
    "love dose": "https://youtu.be/TvngY4unjn4?si=Klb9ajmUNw62F9C0",
    "Tum Hi Ho": "https://youtu.be/Umqb9KENgmk",
    "Chaiyya Chaiyya": "https://youtu.be/PZ7-rpQoK1Y",
    "Kal Ho Naa Ho": "https://youtu.be/sK7riqg2mr4",
    "Tujh Mein Rab Dikhta Hai": "https://youtu.be/VhCajq5PZyg",
    "Pee Loon": "https://youtu.be/eg2Z5E_P_Jk",
    "Tera Ban Jaunga": "https://youtu.be/ToK6FATuoZQ",
    "Raabta": "https://youtu.be/0zJHdA0pL0I",
    "Tareefan": "https://youtu.be/B8gFZvPsVmQ",
    "Nashe Si Chadh Gayi": "https://youtu.be/PVxc5mIHVuQ",
    "Kabira": "https://youtu.be/jHNNMj5bNQw",
    "Tujhe Kitna Chahne Lage": "https://youtu.be/A0FZIwabctw",
    "Bekhayali": "https://youtu.be/VYpOFimB7ZA",
    "Ghungroo": "https://youtu.be/qQ3jzAV6x9g",
    "Dil Diyan Gallan": "https://youtu.be/sa1GWyWj5zQ",
    "Galliyan": "https://youtu.be/BddP6PYo2gs",
    "Tum Se Hi": "https://youtu.be/ONfQofh3SPc",
    "Kun Faya Kun": "https://youtu.be/T94PHkuydcw",
    "Tera Yaar Hoon Main": "https://youtu.be/J0VjvBzs5rs",
    "Zehnaseeb": "https://youtu.be/BMR6tFQy-8U",
    "Sun Saathiya": "https://youtu.be/UQH6TVaobUc",
    "Laung Da Lashkara": "https://youtu.be/gKXgVcuGmNw",
    "Kamariya": "https://youtu.be/WrrvHjv1_tM",
    "Kar Gayi Chull": "https://youtu.be/FvY1F21yb7E",
    "Kala Chashma": "https://youtu.be/k4yXQkG2s1E",
    "Badtameez Dil": "https://youtu.be/sTzVbFjD_qU",
    "Malhari": "https://youtu.be/Rm5g-O9KQUg",
    "London Thumakda": "https://youtu.be/r3yxxe66LXs",
    "Desi Girl": "https://youtu.be/IpEXEpg5xwQ",
    "Aankh Marey": "https://youtu.be/u5L4jBgGiEQ",
    "Bom Diggy Diggy": "https://youtu.be/6ZP6Fp-hkK0",
    "Zinda": "https://youtu.be/nZ9x3OdmOJ0",
    "Apna Time Aayega": "https://youtu.be/jFbqXkMTx1w",
    "Gallan Goodiyan": "https://youtu.be/u6BOC7CDUTQ",
    "Cutiepie": "https://youtu.be/16T9nD6R9ZM",
    "High Rated Gabru": "https://youtu.be/9J0sMZcpGAc",
    "Ban Ja Rani": "https://youtu.be/dXc5JX0NFak",
    "Tamma Tamma Again": "https://youtu.be/SBOkF3RJjOs",
    "Dilbar": "https://youtu.be/z0n1aQ3IxWI",
    "She Move It Like": "https://youtu.be/MtVQG3gNzvY",
    "Morni Banke": "https://youtu.be/4QpAZjHFQLQ",
    "Proper Patola": "https://youtu.be/nDHqzqg2h3M",
    "Bom Diggy": "https://youtu.be/1upZz3a-7iM",
    "Kaala Chashma": "https://youtu.be/k4yXQkG2s1E",
    "Saudagar Sauda Kar": "https://youtu.be/gnM2GsmBTfM",
    "Jab Tak": "https://youtu.be/L63DjXbqf7Q",
    "Muskurane": "https://youtu.be/xzvhZSr5G40",
    "Samjhawan": "https://youtu.be/k4yXQkG2s1E"
}
